name: CI/CD Pipeline for TourGuide

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      # 1. Cloner le dépôt
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Installer le JDK 17 (Temurin) et mettre en cache les dépendances Maven
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      # 3. Compiler le projet et exécuter les tests unitaires
      - name: Build and Test with Maven
        run: mvn clean install --batch-mode

      # 4. Packager l'artefact (le JAR exécutable)
      - name: Package Artifact
        run: mvn package --batch-mode

      # 5. Télécharger (upload) l'artefact créé
      - name: Upload Artifact
        uses: actions/upload-artifact@v4.6.0
        with:
          name: tourguide-artifact
          path: target/*.jar
