name: CI/CD Pipeline for TourGuide

# Déclencheurs : se lance sur push et pull request sur la branche main
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Récupérer le code source
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Installer et configurer le JDK (ici Java 17, adapter si besoin)
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      # 3. Compiler le projet et exécuter les tests unitaires
      - name: Build and Test with Maven
        run: mvn clean install --batch-mode

      # 4. Créer l’artefact (jar exécutable)
      - name: Package Artifact
        run: mvn package --batch-mode

      # 5. Archiver l’artefact pour le téléchargement
      - name: Upload Artifact
        uses: actions/upload-artifact@v4.6.0
        with:
          name: tourguide-artifact
          path: target/*.jar
