name: CI/CD Pipeline for TourGuide

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    # Ici, nous utilisons un runner Windows, puisque vos chemins sont en style Windows.
    runs-on: windows-latest

    steps:
      # Étape 1 : Cloner le dépôt
      - name: Checkout code
        uses: actions/checkout@v3

      # Étape 2.1 : Installer et configurer le JDK 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      # Étape 2.2 : Installer et configurer de maven
      - name: Set up Maven
        uses: stCarolas/setup-maven@v4
        with:
          maven-version: '3.8.6'  # Version recommandée, ajustez si nécessaire


      # Étape 3 : Installer manuellement les dépendances locales
      # Nous utilisons la commande "mvn --% install:install-file" pour Windows,
      # en fournissant le chemin complet et l'extension .jar.
      - name: Install local JAR dependencies
        run: |
          mvn --% install:install-file -Dfile=libs/RewardCentral.jar -DgroupId=rewardCentral -DartifactId=rewardCentral -Dversion=1.0.0 -Dpackaging=jar
          mvn --% install:install-file -Dfile=libs/TripPricer.jar -DgroupId=tripPricer -DartifactId=tripPricer -Dversion=1.0.0 -Dpackaging=jar
          mvn --% install:install-file -Dfile=libs/gpsUtil.jar -DgroupId=gpsUtil -DartifactId=gpsUtil -Dversion=1.0.0 -Dpackaging=jar

      # Étape 4.1 : Compiler le projet
      - name: Compiler le projet
        run: mvn compile --batch-mode

      # Étape 4.2 : exécuter les tests unitaires
      - name: Run tests with Maven
        run: mvn test --batch-mode

      # Étape 5 : Packager l'artefact (le JAR exécutable)
      - name: Package Artifact
        run: mvn package --batch-mode

      # Étape 6 : Uploader l’artefact généré (le JAR dans le dossier target)
      - name: Upload Artifact
        uses: actions/upload-artifact@v4.6.0
        with:
          name: tourguide-artifact
          path: target/*.jar
